- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3, virtualenv
    apt:
      pkg: # # pacotes
      - python3
      - virtualenv
      update_cache: yes # # atualizar os pct 
    become: true # # execulte como root 
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/alura-cursos/clientes-leo-api.git
      dest: /home/ubuntu/tcc
      version: master
      force: yes 
  - name: Instalando dependencias com pip 
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      requirements: /home/ubuntu/tcc/requirements.txt
  
  - name: Alterando o hosts do settings
    lineinfile: # # acesar uma linha de codigo para alteracao
      path: /home/ubuntu/tcc/setup/settings.py # # caminho
      regexp: 'ALLOWED_HOSTS' # # especificando onde
      line: 'ALLOWED_HOSTS = ["*"]' # # alterar para 
      backrefs: yes
  - name: configurando o banco de dados
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py migrate'
  - name: Carregando dados
    shell: '. /home/ubuntu/tcc/venv/bin/activate; python /home/ubuntu/tcc/manage.py loaddata clientes.json'
  - name: iniciando servidor
    shell: '. /home/ubuntu/tcc/venv/bin/activate; nohup python /home/ubuntu/tcc/manage.py runserver 0.0.0.0:8000 &'