- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3, virtualenv
    apt:
      pkg: # # pacotes
      - python3
      - virtualenv
      update_cache: yes # # atualizar os pct 
    become: true # # execulte como root 
  - name: Git Clone
    ansible.builtin.git:
      repo: https://github.com/alura-cursos/clientes-leo-api.git
      dest: /home/ubuntu/tcc
      version: master
  - name: Instalando dependencias com pip (Django e Django Rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name: # # pcts
        - django
        - djangorestframework
  
  - name: Alterando o hosts do settings
    lineinfile: # # acesar uma linha de codigo para alteracao
      path: /home/ubuntu/tcc/setup/settings.py # # caminho
      regexp: 'ALLOWED_HOSTS' # # especificando onde
      line: 'ALLOWED_HOSTS = ["*"]' # # alterar para 
      backrefs: yes